export { default as useCreateRoom } from "./useCreateRoom";
export { default as useDeleteRoom } from "./useDeleteRoom";
export { default as useEditRoom } from "./useEditRoom";
export { default as useGetRoomById } from "./useGetRoomById";
export { default as useGetRoomByIdEffect } from "./useGetRoomByIdEffect";
export { default as useGetRoomsWithRelations } from "./useGetRoomsWithRelations";
export { default as useGetRoomsWithRelationsEffect } from "./useGetRoomsWithRelationsEffect";
export { default as useRemoveStudentFromRoom } from "./useRemoveStudentFromRoom";
export { default as useRemoveTeacherFromRoom } from "./useRemoveTeacherFromRoom";
